# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
eigen_inv <- function(A) {
    .Call(`_Gmi_eigen_inv`, A)
}

#' @export
eigen_matmul <- function(A, B) {
    .Call(`_Gmi_eigen_matmul`, A, B)
}

